# Minimal stub for the one autograd type that appears in surpyval's own
# signatures. autograd ships no type information, so without this mypy
# sees ``ArrayBox`` as a value rather than a class and rejects it in a
# union with "Variable is not valid as a type" -- which is why the
# distribution parameters were annotated ``Any`` before this existed.
#
# The rest of autograd is still resolved by ``ignore_missing_imports``;
# only this module is described, and only as far as surpyval needs.
#
# The operators are what a distribution does to its parameters: every
# arithmetic form in ``sf``/``ff``/``df``/``hf``/``Hf``/``qf``, in both
# operand orders, since ``x / alpha`` reaches the box through its
# reflected method. A missing one is a false positive rather than a
# silent hole -- add it here when a distribution needs it.

from typing import Any

class ArrayBox:
    _value: Any
    def __init__(self, value: Any, trace: Any, node: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __len__(self) -> int: ...
    def __getitem__(self, idx: Any) -> ArrayBox: ...
    def __neg__(self) -> ArrayBox: ...
    def __pos__(self) -> ArrayBox: ...
    def __abs__(self) -> ArrayBox: ...
    def __add__(self, other: Any) -> ArrayBox: ...
    def __radd__(self, other: Any) -> ArrayBox: ...
    def __sub__(self, other: Any) -> ArrayBox: ...
    def __rsub__(self, other: Any) -> ArrayBox: ...
    def __mul__(self, other: Any) -> ArrayBox: ...
    def __rmul__(self, other: Any) -> ArrayBox: ...
    def __truediv__(self, other: Any) -> ArrayBox: ...
    def __rtruediv__(self, other: Any) -> ArrayBox: ...
    def __floordiv__(self, other: Any) -> ArrayBox: ...
    def __rfloordiv__(self, other: Any) -> ArrayBox: ...
    def __mod__(self, other: Any) -> ArrayBox: ...
    def __rmod__(self, other: Any) -> ArrayBox: ...
    def __pow__(self, other: Any) -> ArrayBox: ...
    def __rpow__(self, other: Any) -> ArrayBox: ...
    def __matmul__(self, other: Any) -> ArrayBox: ...
    def __rmatmul__(self, other: Any) -> ArrayBox: ...
    def __lt__(self, other: Any) -> Any: ...
    def __le__(self, other: Any) -> Any: ...
    def __gt__(self, other: Any) -> Any: ...
    def __ge__(self, other: Any) -> Any: ...
