# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:

# Organise imports (configured via [tool.isort] in pyproject.toml)
-   repo: https://github.com/PyCQA/isort
    rev: '8.0.1'
    hooks:
    -   id: isort

# Update all old python syntax
-   repo: https://github.com/asottile/pyupgrade
    rev: 'v3.21.2'
    hooks:
    -   id: pyupgrade
        args: ["--py311-plus"]

# Format with Black (configured via [tool.black] in pyproject.toml)
-   repo: https://github.com/psf/black
    rev: '26.5.1'
    hooks:
    -   id: black

# Lint with flake8 (configured via [tool.flake8] in pyproject.toml)
-   repo: https://github.com/PyCQA/flake8
    rev: '7.3.0'
    hooks:
    -   id: flake8
        additional_dependencies: [Flake8-pyproject]

# It uses the locally installed (need mypy installed locally) since the mirror
# by default uses opionated args
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
